package cc.learn.po;

import java.util.Date;

public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cedarDB..user.id
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cedarDB..user.create_date
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    private Date createDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cedarDB..user.update_date
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    private Date updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cedarDB..user.user_name
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    private String userName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cedarDB..user.create_user
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    private String createUser;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cedarDB..user.update_user
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cedarDB..user.id
     * @return  the value of cedarDB..user.id
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cedarDB..user.id
     * @param id  the value for cedarDB..user.id
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cedarDB..user.create_date
     * @return  the value of cedarDB..user.create_date
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cedarDB..user.create_date
     * @param createDate  the value for cedarDB..user.create_date
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cedarDB..user.update_date
     * @return  the value of cedarDB..user.update_date
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cedarDB..user.update_date
     * @param updateDate  the value for cedarDB..user.update_date
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cedarDB..user.user_name
     * @return  the value of cedarDB..user.user_name
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cedarDB..user.user_name
     * @param userName  the value for cedarDB..user.user_name
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cedarDB..user.create_user
     * @return  the value of cedarDB..user.create_user
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cedarDB..user.create_user
     * @param createUser  the value for cedarDB..user.create_user
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cedarDB..user.update_user
     * @return  the value of cedarDB..user.update_user
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cedarDB..user.update_user
     * @param updateUser  the value for cedarDB..user.update_user
     * @mbg.generated  Wed Jan 16 17:42:03 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}